BDXContext = []
pointer = []
penPos = []
blockPalette = []
resultList = []
runtimeIdsBlockPalette = []
successStates = []
functionName = []
operation = []
lsSave = []
recordBlockEntityData = []
recordBlockEntityDataErrorList = []
blockStatesError = []

def reset():
    global BDXContext,pointer,penPos,blockPalette,resultList,runtimeIdsBlockPalette,successStates,functionName,operation,lsSave,recordBlockEntityData,recordBlockEntityDataErrorList,blockStatesError
    BDXContext = []
    pointer = []
    penPos = []
    blockPalette = []
    resultList = []
    runtimeIdsBlockPalette = []
    successStates = []
    functionName = []
    operation = []
    lsSave = []
    recordBlockEntityData = []
    recordBlockEntityDataErrorList = []
    blockStatesError = []